/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Feedback */
        post: operations["submit_feedback_api_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecasts/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rent Queue */
        get: operations["rent_queue_api_v1_forecasts_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecasts/rent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forecast Rent */
        post: operations["forecast_rent_api_v1_forecasts_rent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecasts/{prediction_id}/rationale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rationale */
        post: operations["rationale_api_v1_forecasts__prediction_id__rationale_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/governance/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Trail */
        get: operations["audit_trail_api_v1_governance_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/governance/cards/{model_name}/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Card */
        get: operations["model_card_api_v1_governance_cards__model_name___version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/governance/drift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Drift */
        get: operations["drift_api_v1_governance_drift_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/governance/kill-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kill Switch State
         * @description Current baseline-mode flag. Analysts may read it (the UI banners on it);
         *     only admins may flip it.
         */
        get: operations["kill_switch_state_api_v1_governance_kill_switch_get"];
        put?: never;
        /**
         * Set Kill Switch
         * @description Flip the API into (or out of) baseline mode without a redeploy. The flag
         *     lives in the DB so it survives a restart and takes effect on the next
         *     request; the flip is an audited action (§8.6).
         */
        post: operations["set_kill_switch_api_v1_governance_kill_switch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/governance/lineage/{prediction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lineage */
        get: operations["lineage_api_v1_governance_lineage__prediction_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models Active */
        get: operations["models_active_api_v1_models_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{model_name}/versions/{version}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve
         * @description Human approval gate. Runs sync (registry helper) in the threadpool.
         */
        post: operations["approve_api_v1_models__model_name__versions__version__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio Summary */
        get: operations["portfolio_summary_api_v1_portfolio_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Risk Queue */
        get: operations["risk_queue_api_v1_risk_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Score Tenant */
        post: operations["score_tenant_api_v1_risk_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tenant Detail */
        get: operations["tenant_detail_api_v1_risk_tenants__tenant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Unauthenticated liveness probe. `models_ready` reflects whether approved
         *     models were loaded — false is a valid booted state (DB still warming).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEventOut */
        AuditEventOut: {
            /** Actor */
            actor: string;
            /** Actor Role */
            actor_role: string;
            /** Entity Id */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Event Type */
            event_type: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Request Id */
            request_id: string | null;
        };
        /** CompOut */
        CompOut: {
            /** Comp Id */
            comp_id: string;
            /** Free Rent Months */
            free_rent_months: number;
            /** Rent Psf */
            rent_psf: number;
            /** Signed Date */
            signed_date: string;
            /** Submarket */
            submarket: string;
            /** Term Months */
            term_months: number;
            /** Ti Allowance Psf */
            ti_allowance_psf: number;
        };
        /** DriftMetricOut */
        DriftMetricOut: {
            /** Baseline Window */
            baseline_window: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Current Window */
            current_window: string;
            /** Feature Name */
            feature_name: string;
            /** Model Name */
            model_name: string;
            /** Psi */
            psi: number;
            /**
             * Status
             * @enum {string}
             */
            status: "green" | "amber" | "red";
        };
        /** ExpirationMonth */
        ExpirationMonth: {
            /** Annual Rent Expiring */
            annual_rent_expiring: number;
            /** Leases Expiring */
            leases_expiring: number;
            /**
             * Month
             * Format: date
             */
            month: string;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "accept" | "override";
            /** Comment */
            comment?: string | null;
            /** Override Value */
            override_value?: {
                [key: string]: unknown;
            } | null;
            /**
             * Prediction Id
             * Format: uuid
             */
            prediction_id: string;
            /** Reason Code */
            reason_code?: string | null;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Action */
            action: string;
            /**
             * Feedback Id
             * Format: uuid
             */
            feedback_id: string;
            /**
             * Prediction Id
             * Format: uuid
             */
            prediction_id: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KillSwitchRequest */
        KillSwitchRequest: {
            /** Baseline Mode */
            baseline_mode: boolean;
            /** Reason */
            reason: string;
        };
        /** KillSwitchState */
        KillSwitchState: {
            /** Baseline Mode */
            baseline_mode: boolean;
        };
        /** LineageOut */
        LineageOut: {
            /** Approved At */
            approved_at: string | null;
            /** Approved By */
            approved_by: string | null;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Baseline Mode */
            baseline_mode: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dq Report Uri */
            dq_report_uri: string | null;
            /** Entity Id */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /** Eval Set Hash */
            eval_set_hash: string | null;
            /** Features */
            features: {
                [key: string]: number;
            };
            /** Feedback */
            feedback: {
                [key: string]: unknown;
            }[];
            /** Git Sha */
            git_sha: string | null;
            /** Model Metrics */
            model_metrics: {
                [key: string]: number;
            } | null;
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: number;
            /** Output */
            output: {
                [key: string]: unknown;
            };
            /**
             * Prediction Id
             * Format: uuid
             */
            prediction_id: string;
            /** Training Snapshot Uri */
            training_snapshot_uri: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Token */
            token: string;
            /** Username */
            username: string;
        };
        /** ModelVersionOut */
        ModelVersionOut: {
            /** Approved At */
            approved_at: string | null;
            /** Approved By */
            approved_by: string | null;
            /** Baseline Metrics */
            baseline_metrics: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dq Report Uri */
            dq_report_uri: string;
            /** Eval Set Hash */
            eval_set_hash: string;
            /** Git Sha */
            git_sha: string;
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
            /** Model Card Path */
            model_card_path: string;
            /** Model Name */
            model_name: string;
            /** Status */
            status: string;
            /** Training Snapshot Uri */
            training_snapshot_uri: string;
            /** Version */
            version: number;
        };
        /** PaymentRow */
        PaymentRow: {
            /** Amount Due */
            amount_due: number;
            /** Amount Paid */
            amount_paid: number;
            /** Days Late */
            days_late: number | null;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /** Lease Id */
            lease_id: string;
            /** Paid Date */
            paid_date: string | null;
        };
        /** PortfolioSummary */
        PortfolioSummary: {
            /** Active Leases */
            active_leases: number;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Avg Pd */
            avg_pd: number;
            /** Expiration Wall */
            expiration_wall: components["schemas"]["ExpirationMonth"][];
            /** N Properties */
            n_properties: number;
            /** N Units */
            n_units: number;
            /** Noi At Risk Annual */
            noi_at_risk_annual: number;
            /** Renewal Upside Annual */
            renewal_upside_annual: number;
            /** Risk Histogram */
            risk_histogram: {
                [key: string]: number;
            }[];
            /** Total Rsf */
            total_rsf: number;
            /** Watchlist Count */
            watchlist_count: number;
        };
        /** RationaleResponse */
        RationaleResponse: {
            /** Backend */
            backend: string;
            /** Fallback Used */
            fallback_used: boolean;
            /** Guard Passed */
            guard_passed: boolean;
            /**
             * Label
             * @default AI-generated explanation
             */
            label: string;
            /** Memo */
            memo: string;
            /** Payload Hash */
            payload_hash: string;
            /**
             * Prediction Id
             * Format: uuid
             */
            prediction_id: string;
        };
        /** RentForecastRequest */
        RentForecastRequest: {
            /** Unit Id */
            unit_id: string;
        };
        /** RentForecastResponse */
        RentForecastResponse: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Asset Class */
            asset_class: string;
            /** Baseline Mode */
            baseline_mode: boolean;
            /** Comp Median Rent 6M */
            comp_median_rent_6m: number;
            /** Comps */
            comps: components["schemas"]["CompOut"][];
            /** Current Rent Psf */
            current_rent_psf: number;
            /** Current Tenant Id */
            current_tenant_id: string | null;
            /** Drivers */
            drivers: components["schemas"]["ShapDriverOut"][];
            /**
             * Lease Expiration
             * Format: date
             */
            lease_expiration: string;
            /** Model Version */
            model_version: number;
            /** P10 */
            p10: number;
            /** P50 */
            p50: number;
            /** P90 */
            p90: number;
            /**
             * Prediction Id
             * Format: uuid
             */
            prediction_id: string;
            /** Property Name */
            property_name: string;
            /** Submarket */
            submarket: string;
            /** Unit Id */
            unit_id: string;
            /** Unit Rsf */
            unit_rsf: number;
        };
        /** RentQueueItem */
        RentQueueItem: {
            /** Asset Class */
            asset_class: string;
            /** Baseline Mode */
            baseline_mode: boolean;
            /** Current Rent Psf */
            current_rent_psf: number;
            /** Floor */
            floor: number;
            /**
             * Lease Expiration
             * Format: date
             */
            lease_expiration: string;
            /** Market */
            market: string;
            /** P10 */
            p10: number;
            /** P50 */
            p50: number;
            /** P90 */
            p90: number;
            /**
             * Prediction Id
             * Format: uuid
             */
            prediction_id: string;
            /** Property Name */
            property_name: string;
            /** Submarket */
            submarket: string;
            /** Unit Id */
            unit_id: string;
            /** Unit Rsf */
            unit_rsf: number;
            /** Upside Pct */
            upside_pct: number;
        };
        /** RiskQueueItem */
        RiskQueueItem: {
            /**
             * Band
             * @enum {string}
             */
            band: "green" | "amber" | "red";
            /** Baseline Mode */
            baseline_mode: boolean;
            /** Credit Rating */
            credit_rating: string | null;
            /** Industry */
            industry: string;
            /** Model Version */
            model_version: number;
            /** Monthly Rent Due */
            monthly_rent_due: number;
            /** Pd */
            pd: number;
            /**
             * Prediction Id
             * Format: uuid
             */
            prediction_id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Tenant Name */
            tenant_name: string;
            /** Top Driver */
            top_driver: string;
            /**
             * Trend
             * @description Monthly mean days-late, last 12 months
             */
            trend: number[];
        };
        /** RiskScoreRequest */
        RiskScoreRequest: {
            /** Tenant Id */
            tenant_id: string;
        };
        /** RiskScoreResponse */
        RiskScoreResponse: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Band
             * @enum {string}
             */
            band: "green" | "amber" | "red";
            /** Baseline Mode */
            baseline_mode: boolean;
            /** Drivers */
            drivers: components["schemas"]["ShapDriverOut"][];
            /** Model Version */
            model_version: number;
            /**
             * Pd
             * @description Calibrated probability of default within 6 months
             */
            pd: number;
            /**
             * Prediction Id
             * Format: uuid
             */
            prediction_id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Tenant Name */
            tenant_name: string;
        };
        /** ShapDriverOut */
        ShapDriverOut: {
            /** Feature */
            feature: string;
            /** Label */
            label: string;
            /** Shap */
            shap: number;
            /** Value */
            value: number;
        };
        /** TenantDetail */
        TenantDetail: {
            /** Credit Rating */
            credit_rating: string | null;
            /** Industry */
            industry: string;
            latest: components["schemas"]["RiskScoreResponse"] | null;
            /** Leases */
            leases: components["schemas"]["TenantLease"][];
            /** Name */
            name: string;
            /** Payment History */
            payment_history: components["schemas"]["PaymentRow"][];
            /** Score History */
            score_history: {
                [key: string]: unknown;
            }[];
            /** Tenant Id */
            tenant_id: string;
        };
        /** TenantLease */
        TenantLease: {
            /** Asset Class */
            asset_class: string;
            /** Base Rent Psf */
            base_rent_psf: number;
            /**
             * Commencement
             * Format: date
             */
            commencement: string;
            /**
             * Expiration
             * Format: date
             */
            expiration: string;
            /** Lease Id */
            lease_id: string;
            /** Lease Type */
            lease_type: string;
            /** Property Name */
            property_name: string;
            /** Submarket */
            submarket: string;
            /** Term Months */
            term_months: number;
            /** Unit Id */
            unit_id: string;
            /** Unit Rsf */
            unit_rsf: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_api_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rent_queue_api_v1_forecasts_queue_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RentQueueItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_rent_api_v1_forecasts_rent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RentForecastRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RentForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rationale_api_v1_forecasts__prediction_id__rationale_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prediction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RationaleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_trail_api_v1_governance_audit_get: {
        parameters: {
            query?: {
                event_type?: string | null;
                entity_id?: string | null;
                actor?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_card_api_v1_governance_cards__model_name___version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_name: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drift_api_v1_governance_drift_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriftMetricOut"][];
                };
            };
        };
    };
    kill_switch_state_api_v1_governance_kill_switch_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KillSwitchState"];
                };
            };
        };
    };
    set_kill_switch_api_v1_governance_kill_switch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KillSwitchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KillSwitchState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lineage_api_v1_governance_lineage__prediction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prediction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_active_api_v1_models_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelVersionOut"][];
                };
            };
        };
    };
    approve_api_v1_models__model_name__versions__version__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_name: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_summary_api_v1_portfolio_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"];
                };
            };
        };
    };
    risk_queue_api_v1_risk_queue_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskQueueItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_tenant_api_v1_risk_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tenant_detail_api_v1_risk_tenants__tenant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
